<?php

namespace ContentElementsManagementSystemBundle\Repository;

/**
 * BlocSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
