<?php

namespace ContentElementsManagementSystemBundle\Repository;

/**
 * BlocTextRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocTextRepository extends \Doctrine\ORM\EntityRepository
{
}
