<?php

namespace ContentElementsManagementSystemBundle\Repository;

/**
 * BlocImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocImageRepository extends \Doctrine\ORM\EntityRepository
{
}
