<?php

namespace ContentElementsManagementSystemBundle\Repository;

/**
 * BlocSectionTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocSectionTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
