stfalcon_tinymce:
    external_plugins: { filemanager: { url: 'asset[bundles/stfalcontinymce/vendor/tinymce/plugins/filemanager/plugin.min.js]' } }
    selector: .tinymce
    theme: { simple: { height: 150, plugins: ['advlist autolink lists link image charmap print preview hr anchor pagebreak', 'searchreplace wordcount visualblocks visualchars code fullscreen', 'insertdatetime media nonbreaking save table contextmenu directionality', 'emoticons template paste textcolor jbimages filemanager'], toolbar: 'insertfile undo redo |filemanager| styleselect | forecolor | backcolor | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link jbimages | code | hr', image_advtab: true, relative_urls: false, external_filemanager_path: 'http://127.0.0.1:8000/bundles/stfalcontinymce/vendor/tinymce/plugins/filemanager/', filemanager_title: 'Gestionnaire de fichiers' } }
knp_doctrine_behaviors:
    blameable: false
    geocodable: null
    loggable: null
    sluggable: true
    soft_deletable: true
    translatable: true
#twig:
    #form_themes: 
        #- '@AdminBundle\Resources\views\Default\forms.html.twig'
