parameters:
    locale: es
a2lix_translation_form:
    locale_provider: default
    locales: [fr, es, hn]
    default_locale: es
    required_locales: [es]
    templating: '@A2lixTranslationForm/default.html.twig'
framework:
    translator: { fallbacks: [es] }
