parameters:
    locale: fr
a2lix_translation_form:
    locale_provider: default
    locales: [fr]
    default_locale: fr
    templating: '@AdminBundle\Resources\views\Templates\Locales\forms.html.twig'
framework:
    translator: { fallbacks: [fr] }
