parameters:
    locale: fr
a2lix_translation_form:
    locale_provider: default
    locales: [fr]
    default_locale: fr
    templating: '@CoreSystemBundle\Resources\views\Templates\Locales\translations_forms.html.twig'
    required_locales: [fr]
framework:
    translator: { fallbacks: [fr] }
