# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
    app.tblprefix_subscriber:
        class: AdminBundle\Subscriber\TablePrefixSubscriber
        arguments: [%app.db.table_prefix%]
        tags:
            - { name: doctrine.event_subscriber }
    admin.image_uploader:
        class: AdminBundle\Service\FileUploader
        arguments: ['%uploads_directory%']
    admin.doctrine_image_listener:
        class: AdminBundle\EventListener\ImageUploadListener
        arguments: ['@admin.image_uploader']
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }