<?php

namespace ContentElementsManagementSystemBundle\Repository;

/**
 * BlocTextTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocTextTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
