<?php

namespace ContentElementsManagementSystemBundle\Repository;

/**
 * BlocGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocGalleryRepository extends \Doctrine\ORM\EntityRepository
{
}
