<?php

namespace ContentElementsManagementSystemBundle\Repository;

/**
 * BlocGalleryimageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocGalleryimageRepository extends \Doctrine\ORM\EntityRepository
{
}
