<?php

namespace ContentElementsManagementSystemBundle\Repository;

/**
 * BlocQuoteTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocQuoteTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
