<?php

namespace ContentElementsManagementSystemBundle\Repository;

/**
 * BlocQuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlocQuoteRepository extends \Doctrine\ORM\EntityRepository
{
}
