<?php

namespace CoreSystemBundle\Repository;

/**
 * HelpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HelpRepository extends \Doctrine\ORM\EntityRepository
{
}
