<?php

namespace CoreSystemBundle\Repository;

/**
 * SeoTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
