var _path = "_adminAssets"
$.getScript("https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js",function(){})
$.getScript("https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js",function(){})
$.getScript("https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js",function(){})
$.getScript("https://code.jquery.com/ui/1.12.1/jquery-ui.js",function(){})
$.getScript("/"+ _path +"/_libs/croppie/croppie.min.js",function(){})
$.getScript("/"+ _path +"/_libs/pnotify/dist/pnotify.js",function(){})
$.getScript("/"+ _path +"/_libs/pnotify/dist/pnotify.buttons.js",function(){})
$.getScript("/"+ _path +"/_libs/pnotify/dist/pnotify.nonblock.js",function(){})
$.getScript("/"+ _path +"/_libs/sweetalert/sweetalert2.all.min.js",function(){})
$.getScript("/"+ _path +"/_libs/speakingurl.min.js",function(){})
$.getScript("/"+ _path +"/_libs/jquery.stringtoslug.min.js",function(){})
$.getScript("/"+ _path +"/_libs/select2.min.js",function(){})
$.getScript("/"+ _path +"/_libs/sortable.js",function(){})