<?php

namespace MediaBundle\Repository;

/**
 * PageAndImageRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageAndImageRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
