<?php

namespace AdminBundle\Repository;

/**
 * CantactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CantactRepository extends \Doctrine\ORM\EntityRepository
{
}
