<?php

namespace AdminBundle\Repository;

/**
 * CategoryTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
