<?php

namespace AdminBundle\Repository;

/**
 * HomeTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
