<?php

namespace AdminBundle\Repository;

/**
 * HomeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomeRepository extends \Doctrine\ORM\EntityRepository
{
}
