<?php

namespace AdminBundle\Repository;

/**
 * LocationTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
