<?php

namespace AdminBundle\Repository;

/**
 * PressTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PressTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
