<?php

namespace AdminBundle\Repository;

/**
 * ProjectTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
