<?php

namespace AdminBundle\Repository;

/**
 * SettingsTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SettingsTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
